#include "prometheus-mqttbroker-stats-exporter.h"
#include <mosquitto.h>
#include <stdio.h>

void usage(void) {
    int major, minor, revision;

    mosquitto_lib_version(&major, &minor, &revision);

    fprintf(stdout, "prometheus-mqttbroker-stats-exporter version %s\n"
            "Copyright (C) by Andreas Maus <maus@ypbind.de>\n"
            "This program comes with ABSOLUTELY NO WARRANTY.\n"
            "\n"
            "prometheus-mqttbroker-stats-exporter is distributed under the terms of the GNU General\n"
            "Public License Version 3. (http://www.gnu.org/copyleft/gpl.html)\n"
            "\n"
            "Linked Mosquitto library version %u.%u.%u\n\n"
            "Usage: prometheus-mqttbroker-stats-exporter [-h|--help] [-u <user>|--user=<user>] \n"
            "   [-p <password>|--password=<password>] [-c <cert_file>|--cert-file=<cert_file>] [-k <key_file>|--key-file=<key_file>]\n"
            "   [-C <ca_file>|--ca-file=<ca_file>] [-D <ca_dir>|--ca-dir=<ca_dir>] [-i|--insecure] -H <host>|--host=<host>\n"
            "   [-P <port>|--port=<port>] [-K <keeapalive>|--keepalive=<keepalive>] [-Q <qos>|--qos=<qos>] [-t <timeout>|--timeout=<timeout>]\n"
            "   [-f <pass_file>|--password-file=<pass_file>] [-s|--ssl] [-d|--debug]\n"
            "\n"
            "   -h  This text\n"
            "   --help\n"
            "\n"
            "   -u <user>                       Authenticate as <user>\n"
            "   --user=<user>                   User/password and SSL client certificate authentication are mutually exclusive\n"
            "\n"
            "   -p <password>                   User <password> for authentication as <user>\n"
            "   --password=<password>           User/password and SSL client certificate authentication are mutually exclusive\n"
            "\n"
            "   -c <cert_file>                  Authenticate with SSL client certificate\n"
            "   --cert-file=<cert_file>         User/password and SSL client certificate authentication are mutually exclusive\n"
            "\n"
            "   -k <key_file>                   Use private SSL key for SSL client certificate authentication\n"
            "   --key-file=<key_file>           User/password and SSL client certificate authentication are mutually exclusive\n"
            "\n"
            "   -C <ca_file>                    For SSL connection <ca_file> contains the CA certificate\n"
            "   --ca-file=<ca_file>\n"
            "\n"
            "   -D <ca_dir>                     For SSL connection <ca_dir> contains CA certificates\n"
            "   --ca-dir=<ca_dir>\n"
            "\n"
            "   -i                              Don't verify SSL certificate of the broker\n"
            "   --insecure\n"
            "\n"
            "   -H <host>                       Hostname or address of MQTT broker to connect to\n"
            "   --host=<host>                   This option is mandatory\n"
            "\n"
            "   -P <port>                       Port of MQTT broker to connect to\n"
            "   --port=<port>                   Default: 1883\n"
            "\n"
            "   -K <keepalive>                  Send keepalive probes every <keepalive> seconds\n"
            "   --keepalive=<keepalive>\n"
            "\n"
            "   -Q <qos>                        Set MQTT QoS (0,1 or 2)\n"
            "   --qos=<qos>                     Default: 0\n"
            "\n"
            "   -t <timeout>                    MQTT connection timeout in ms\n"
            "   --timeout=<timeout>             Default: 1000\n"
            "\n"
            "   -f <pass_file>                  Read password for user/password authentication from <pass_file>\n"
            "   --password-file=<pass_file>\n"
            "\n"
            "   -s                              Use SSL\n"
            "   --ssl\n"
            "\n"
            "   -d                              Enable debug outout\n"
            "   --debug"
            "\n"
            "-l <port>                          Run on <port> for metrics export to Prometheus\n"
            "--listen=<port>                    Default: 11883\n"
            "\n"
            "\n", PROMETHEUS_MQTTBROKER_STATS_EXPORTER_VERSION, major, minor, revision);
};

